### ISSUE TITLE
Goes to beer o'clock when its one minute to go

### ISSUE THREAD

**Issue by marcusgustafson** [jamesrwhite/beeroclock#7]
I've Noticed a fatal error in the count down. While sitting there, patiently waiting with a cold beer in my hand and the counter has one minute to go it suddenly switches to "Beer o'clock". Leaving me no time to find an opener or even a suitable glass. This is an outrage! :)

**Comment by jamesrwhite** [comment]
You need to be more prepared 😉

Cheers! 🍻
